disabled: false
reporter:
    logSpans: true
    localAgentHostPort: 127.0.0.1:6831
    queueSize: 300
sampler:
  type: const
  param: 1
  #maxOperations: 2000 (default)
  #samplingServerURL : (default)

